FROM grupoavispa/oatpp:1.3.0-jammy AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y \
    cmake \
    make \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy everything from src/ (since dockerfile is inside src/)
COPY . .

RUN mkdir -p build && cd build \
    && cmake .. -DCMAKE_BUILD_TYPE=Release \
    && make -j$(nproc)

FROM ubuntu:jammy

WORKDIR /app
COPY --from=builder /app/build/my-oatpp-app .

EXPOSE 8000
CMD ["./my-oatpp-app"]